### ISSUE TITLE
Amazon Builders on t3 instances have unlimited credits enabled by default

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-amazon#127]
_This issue was originally opened by @ricardclau in https://github.com/hashicorp/packer/issues/6721 and has been migrated to this repository. The original issue description is below._

---
This is related to https://github.com/hashicorp/packer/issues/6260 and it happens with all packer versions

AWS recently launched t3 instances which have better network performance (and are slightly cheaper) than the previous t2 family

However, they come with a hidden surprise, unlimited credits seems to be on by default

I guess it should be a relatively easy fix. Code in the mentioned issue should be slightly modified so that unlimited credits is explicitly set to false by default and only set to true if the packer user decides to

If nobody wants to pick this up, I may have some time to work on it!

**Comment by nirvana-msu** [comment]
This has been open for well over 4 years.. there still appears to be no way to disable unlimited credits for T4G and the like. It is a really basic and much needed setting.

**Comment by nirvana-msu** [comment]
The support for this has recently been [added to Terraform](https://github.com/hashicorp/terraform-provider-aws/issues/15156). Can same be done for Packer, please?

**Comment by nywilken** [comment]
Hi @nirvana-msu @AlbertusVermeulen thanks for bubbling this issue up. I lost sight of it. I will work on getting this prioritized so that I can get the cycles to close this out.

**Comment by nywilken** [comment]
Hello :wave: thanks again keeping this thread going. This should be fixed by #273  some test binaries are available via the link below if you would like to test the fix. By default the use of these instance types T2/T3/T3a/T4g will have their credit specification set to "standard". Setting the new input argument `enable_unlimited_credits` to true will use set the cpu credits specification to "unlimited". T2 instances do not support unlimited credits when running as a spot instance. But that is not the case for T3/T3a/T4g types. Please give the test binaries a run and let us know if they resolve the issues around extra costs. 

https://app.circleci.com/pipelines/github/hashicorp/packer-plugin-amazon/346/workflows/30b24d71-ad60-4c8c-b497-6c9769604463/jobs/4269/artifacts

**Comment by nirvana-msu** [comment]
It's a bit of a hassle to install the plugin manually 😅, but I'll check it when it's released. Thanks for a quick turnaround!

**Comment by nywilken** [comment]
> It's a bit of a hassle to install the plugin manually 😅, but I'll check it when it's released. Thanks for a quick turnaround!

That's fair. I'll work with the team to get this out this week, if not today.

**Comment by nywilken** [comment]
Folks this request has been addressed in #273. It set to be released tomorrow Thursday September 28, 2022.

**Comment by ricardclau** [comment]
Glad to see this fixed after almost 4 years from opening the issue!
