### ISSUE TITLE
Packer insist on putting "Packer Builder" tag

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-amazon#155]
_This issue was originally opened by @grumpper in https://github.com/hashicorp/packer/issues/11370 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

When I am running packer build it puts `Name = "Packer Builder"` on the temp instance used for building and on the AMI itself. This happens when I don't put `tags` and `run_tags` at all or even when explicitly set them to be `{}`.

#### Reproduction Steps

Define packer template and setup the `amazon-ebs` source.
Remove any tagging config from the source OR set it to `{}` explicitly.
Use the template to build something and observe how both the instance and the AMI created from it are tagged nevertheless.

### Packer version

Tested on packer `1.7.7` and `1.7.8`

### Simplified Packer Template
```
source "amazon-ebs" "stuff" {
  ami_name                      = "${var.ami_base_name}-${var.source_version}-hvm-${formatdate("YYYYMMDD", timestamp())}-x86_64-gp2"
/.../
  tags          = {}
  run_tags   = {}
/.../
}

build {
  sources = [
    "source.amazon-ebs.stuff.id"
  ]

  provisioner "shell" {
    inline = [
      "echo \"some script stuff\""
    ]
  }
}

### Operating system and Environment details

macOS 12.0.1 (x86_64)

### Log Fragments and crash.log files

no errors in logs; it's just that this behavior is nonsense cause you have means to control the tags you want but you actually don't since packer decides to put one anyway no matter your config.
When building an AMI for clients who do not give permissions to tag AMIs since they want to control that themselves the build directly errors out. And there is no way to work around that.

**Comment by grumpper** [comment]
Some more info about this:

I checked and initially this default tag was added because some guy was having difficulties guessing which instance is run by packer so Mitchell just decided to hard-code that:

https://github.com/hashicorp/packer/issues/642

I guess this was somewhat viable solution in 2013 but now that we support the `tags` and `run_tags` attributes to define whatever we need I think this needs to be reworked.

Some more info about the issue:

I tested running the same template with packer 1.7.3 and for some reason it does not try to tag the AMI.
Nothing in the changelog gives me a hint what "regression" could have been implemented.

Mitchell's commit is related to the run instance but I have no idea how the AMI gets created with that tag as well in 1.7.7 and 1.7.8.
I even tested by removing the tag from the run instance immediately after launch cause I thought the AMI just inherits whatever tag is present on the run instance but it tried to put the tag on the AMI anyway.

Anyway...

My current issue in my specific use case is with the AMI tagging but to summarize again:

If we have `tags` for the AMI and `run_tags` for the run instance then this should be the explicit and exclusive tag configuration (as intended) and no other tags should jump in out of the blue because a guy in 2013 had troubles telling which instance is the packer one because he did not put tags to anything in its account. 

:)

**Comment by lorengordon** [comment]
This name tag on the created AMIs was annoying me also! But I figured out I was able to work around it by setting:

```
tags = { Name = "" } # Empty name tag avoids inheriting "Packer Builder"
```

It's not quite the same as having no Name tag, but at least it displays as empty in the console.

**Comment by marco-m-pix4d** [comment]
This seemingly innocuous change actually breaks periodic scripts that reap running AMIs left over by Packer.
