### ISSUE TITLE
EBS builder - Feature to add tags to temporary role created 

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-amazon#322]
_This issue was originally opened by @l3LUM in https://github.com/hashicorp/packer/issues/12236 and has been migrated to this repository. The original issue description is below._

---
I want to use the [temporary_iam_instance_profile_policy_document](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#temporary_iam_instance_profile_policy_document) on the [amazon-ebs builder](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs) to authorise instance managed by packer to get access to a bucket.

My compagny enforce all new IAM roles to have specific tags, but I couldn't find any argument to add a tag to the temporary role created. So Packer failed at start when creating temporary resources.

Is there a workaround to add tags to the temporary created role ?

Or could you make a feature that adds a "tags" field for the temporary_iam_instance_profile_policy_document option ?

**Comment by Glyphack** [comment]
Hi @l3LUM

I think the current workaround would be to create the role yourself and pass the profile to packer instead of creating a temporary one.

Seems like the role is created [here](https://github.com/Glyphack/packer-plugin-amazon/blob/d4d7aa39f6ec965d148c692aead7567dd5a17f66/builder/common/step_iam_instance_profile.go#L64), and probably we can pass tags here.

**Comment by l3LUM** [comment]
Thanks for your answer, Indeed it's the solution i've choosed as a workaround.
I think it would be a great feature because It makes my CI/CD pipeline more complex as I only want to use this policy temporarily. 

For now, I created a stack Terraform that creates a policy, role and instance profile. This stack is deployed before I run packer and destroyed after the build.

So I hope you will add the feature ! :)
